name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: gcc:11.4.0

    steps:
    - uses: actions/checkout@v4
    - name: day01
      working-directory: ./day01
      run: make test
    - name: day02
      working-directory: ./day02
      run: make test
    - name: day03
      working-directory: ./day03
      run: make test
    - name: day04
      working-directory: ./day04
      run: make test
    - name: day05
      working-directory: ./day05
      run: make test
    - name: day07
      working-directory: ./day07
      run: make test
    - name: day08
      working-directory: ./day08
      run: make test
    - name: day09
      working-directory: ./day09
      run: make test
    - name: day10
      working-directory: ./day10
      run: make test
    - name: day11
      working-directory: ./day11
      run: make test
    - name: day14
      working-directory: ./day14
      run: make test
    - name: day15
      working-directory: ./day15
      run: make test
    - name: day18
      working-directory: ./day18
      run: make test
